apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: localstorage-ocs-osd
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
            values:
              - ''
  storageClassDevices:
    - storageClassName: localstorage-ocs-osd-sc
      volumeMode: Block 
      devicePaths:
        - /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29298dd55a14c15e8f49d287e31
        - /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29805a74d74c958feddd2f05e4f
        - /dev/disk/by-id/scsi-SVMware_Virtual_disk_6000c29b5e0f72d158daeddb8e4a6225
