- name: Create Cluster Folder
  vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter_name: "{{ vcenter_datacenter }}"
    folder_name: "{{ cluster_name }}"
    folder_type: vm
    state: present

- name: Upload RHCOS OVA Template
  vmware_deploy_ovf:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vcenter_datastore }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ cluster_name }}"
    allow_duplicates: no
    disk_provisioning: thin
    name: "{{ ova_vm_name }}"
    networks: "{u'VM Network':u'{{ vcenter_network }}'}"
    ova: "{{ ova_path }}"
    power_on: no
  tags:
    - upload-ova

- name: Debug Append Bootstrap Ignition File
  debug:
    msg: "{{ lookup('template', 'templates/append-bootstrap.j2') | to_json | b64encode }}"

- name: Create VMs (Cluster Placement)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ hostvars[item].datastore }}"
    disk: "{{ hostvars[item].disk | default([]) | list }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ cluster_name }}"
    guest_id: rhel8_64Guest
    hardware:
      memory_mb: "{{ hostvars[item].memory }}"
      num_cpus: "{{ hostvars[item].cores }}"
      num_cpu_cores_per_socket: "{{ hostvars[item].cores }}"
    name: "{{ item }}.{{ base_domain }}"
    state: present
    template: "{{ ova_vm_name }}"
    customvalues:
      - key: "guestinfo.ignition.config.data"
        value: "{{ lookup('template', 'templates/append-bootstrap.j2') | to_json | b64encode }}"
      - key: "guestinfo.ignition.config.data.encoding"
        value: base64
      - key: "disk.EnableUUID"
        value: "TRUE"
  register: vmware_guest_results
  with_items:
    - "{{ groups[provision_group] }}"
  when:
    - hostvars[item].hypervisor is not defined

- name: Create VMs (Hypervisor Placement)
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    datastore: "{{ hostvars[item].datastore }}"
    disk: "{{ hostvars[item].disk | default([]) | list }}"
    esxi_hostname: "{{ hostvars[item].hypervisor }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ cluster_name }}"
    guest_id: rhel8_64Guest
    hardware:
      memory_mb: "{{ hostvars[item].memory }}"
      num_cpus: "{{ hostvars[item].cores }}"
      num_cpu_cores_per_socket: "{{ hostvars[item].cores }}"
    name: "{{ item }}.{{ base_domain }}"
    state: present
    template: "{{ ova_vm_name }}"
    customvalues:
      - key: "guestinfo.ignition.config.data"
        value: "{{ lookup('template', 'templates/append-bootstrap.j2') | to_json | b64encode }}"
      - key: "guestinfo.ignition.config.data.encoding"
        value: base64
      - key: "disk.EnableUUID"
        value: "TRUE"
  register: vmware_guest_results
  with_items:
    - "{{ groups[provision_group] }}"
  when:
    - hostvars[item].hypervisor is defined

- name: Get VM Facts
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ item }}.{{ base_domain }}"
  register: vmware_guest_facts_results
  with_items:
    - "{{ groups[provision_group] }}"

- name: Combine Applicable Disks & Hostnames into Dictionary for Easy Lookup
  set_fact:
    disk_name_dict: >-
      {{
        disk_name_dict | default([]) +
        [
          {
            'name': item,
            'disks': hostvars[item].disks | default([])
          }
        ]
      }}
  tags:
    - disks
  with_items:
    - "{{ groups[provision_group] }}"

- name: Add Disks to VMs
  vmware_guest_disk:
    datacenter: "{{ vcenter_datacenter }}"
    disk:
      - size_gb: "{{ item.1.size_gb }}"
        type: thin
        datastore: "{{ item.1.datastore }}"
        scsi_controller: "{{ item.1.scsi_controller }}"
        state: present
        unit_number: "{{ item.1.unit_number }}"
    folder: "/{{ vcenter_datacenter }}/vm/{{ cluster_name }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item.0.name }}.{{ base_domain }}"
    password: "{{ vcenter_password }}"
    username: "{{ vcenter_username }}"
    validate_certs: no
  with_subelements:
    - "{{ disk_name_dict }}"
    - disks
    - skip_missing: False

- name: Combine Hostname/IP/MAC into Dictionary for Easy Lookup
  set_fact:
    host_mac_list: >-
      {{
        host_mac_list | default([]) +
        [
          {
            'name': item.item,
            'mac': item.instance.hw_eth0.macaddress,
            'ip': hostvars[item.item]['ip']
          }
        ]
      }}
  with_items:
    - "{{ vmware_guest_facts_results.results }}"

- name: Debug host_mac_list
  debug:
    var: host_mac_list
